### ISSUE TITLE
Incidencias

### ISSUE THREAD

**Issue by Moipanloz** [Moipanloz/mycrossingtfg#77]
- [x] #1 - Perfil - MisVecinos: cuando abres el menu, puedes scrollear mas abajo del footer
- [x] #2 - Perfil - MisVecinos: cuando abres el menu en el primero o el segundo desde la dcha, el menu se pasa de ancho, modificar la posicion
- [x] #3 - Deleted
- [x] #4 - General: ondas del footer por encima de popups
- [x] #5 - Perfil - Visitas: En ningun momento se popula la BBDD y si no tiene visitas da error en las operaciones siguientes.
- [x] #6 - Perfil - MisVecinos: No se actualizan los vecinos (probablemente tenga algo que ver con la id)
- [x] #7 - Perfil - MisVecinos: cuando abres el menu amistad en el primero desde la dcha, el menu se pasa de ancho, modificar la posicion
- [x] #8 - Cat.Insectos (y probs peces y los otros?) Cuando hay solo una fila se ve borde blanco abajo (fijarse en muebles?)
